/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module decade_counter(clk, reset, count);
  wire [31:0] _0_;
  wire _1_;
  wire _2_;
  input clk;
  wire clk;
  output [3:0] count;
  reg [3:0] count;
  input reset;
  wire reset;
  assign _0_ = count + 32'd1;
  always @(posedge clk)
    if (_1_) count <= 4'h0;
    else count <= _0_[3:0];
  assign _1_ = | { _2_, reset };
  assign _2_ = count == 4'h9;
endmodule

module tb_decade_counter();
  wire reset;
  assign reset = 1'h0;
endmodule
